FROM ubuntu:25.10

ARG ZIG_DIR=repo/zig-aarch64-linux-0.15.2

RUN apt-get update && apt-get install -y --no-install-recommends \
    build-essential \
    bison \
    ca-certificates \
    curl \
    diffutils \
    flex \
    gettext \
    git \
    gnucobol \
    default-jdk \
    golang-go \
    libgmp-dev \
    libsqlite3-dev \
    autoconf \
    automake \
    maven \
    pkg-config \
    texinfo \
    unzip \
    zip \
    xz-utils \
  && rm -rf /var/lib/apt/lists/*

COPY ${ZIG_DIR} /opt/zig
RUN ln -s /opt/zig/zig /usr/local/bin/zig

WORKDIR /work
